### ISSUE TITLE
Warning for deprecation of set-env command

### ISSUE THREAD

**Issue by raiyanalam** [Azure/manage-azure-policy#25]
Seeing this warning when action runs:

![image](https://user-images.githubusercontent.com/7879476/96130046-035ba680-0f15-11eb-88e8-8c9481be83bb.png)

**Comment by raiyanalam** [comment]
@ajinkya599/ @rgsubh  : do we have a timeline in which we'll fix this?

**Comment by rgsubh** [comment]
> @ajinkya599/ @rgsubh : do we have a timeline in which we'll fix this?

Looking into this, should be fixed soon.

**Comment by raiyanalam** [comment]
Adding @shigupt202 as well to comment if he has done some work for this.

**Comment by shigupt202** [comment]
Yes @raiyanalam I've fixed this warning for other actions owned by us. I can work on this but will need some help from someone who has worked on the action already for testing the changes.

**Comment by raiyanalam** [comment]
This is fixed now! Closing.
