### ISSUE TITLE
Add support for policy-as-code with policysets/initiatives

### ISSUE THREAD

**Issue by jesseloudon** [Azure/manage-azure-policy#28]
Please add support for this GHA to export policysets/initiatives and their related initiative assignments from the Azure portal.

I use over 40+ custom policies which are grouped into initiatives and assigned to the subscription scope. This allows me to quickly see/manage the compliance of initiatives at a glance without drilling down into individual policies.

Assigning policies individually to the subscription, or even resource group, becomes hard to manage at scale and across many subscriptions.

**Comment by raiyanalam** [comment]
This capability will be added soon 👍

**Comment by raiyanalam** [comment]
Hi @jesseloudon : We have rolled out the support for initiatives.
![image](https://user-images.githubusercontent.com/7879476/98229071-750c9a80-1f7f-11eb-920c-df1db9cb87c0.png)

**Comment by raiyanalam** [comment]
Closing this. Do let us know if you face any issues in future.
