### ISSUE TITLE
How can we sync the custom policies created in Github to azure portal?

### ISSUE THREAD

**Issue by suneelsunkara** [Azure/manage-azure-policy#44]
Hi,
I understand that we can export azure policies from portal to github. But wanted to understand if there is a way to create a custom policy in Github and the ability to deploy it to Azure portal through GitHub Actions?

Thanks,
Suneel

**Comment by JCDeist** [comment]
I agree with this. We manage multiple tenants and would like to be able to reference the same custom policy in workflows towards different tenants. Right now it seems the process is dependent on the policy already existing in Azure and having a guid.

**Comment by ajinkya599** [comment]
The action supports creating new policies. You have to add the policies to the repo and add their paths as action input. Please refer to the [samples](https://github.com/Azure/manage-azure-policy#end-to-end-sample-workflows) for reference.
The `id` in the policy definition/assignment determines the `scope`. The `SPN` used for `login` should have permissions on these scopes.

**Comment by ajinkya599** [comment]
Do check-out the other thread as well:
https://github.com/Azure/manage-azure-policy/issues/43#issuecomment-801711513
