### ISSUE TITLE
Actions reports success when ARM API return error

### ISSUE THREAD

**Issue by sbugalski** [Azure/manage-azure-policy#45]
Hello,
I have noticed the action report success status when ARM API call fails (at least for assignment).
No conditionals are used for the action.

Bellow two examples:

`
Failed to get policy with id /providers/Microsoft.Management/managementGroups/test-spgi-terraform/providers/Microsoft.Authorization/policyAssignments/Append_NSG_if_missing-4ca69cc5-3a14-4614-9d17-04e0ca2cee70, path config-files/policy/policies/Append_NSG_for_MG/assign.Test-SPGI-Terraform.Append_NSG_if_missing.json. Error : {"code":"InvalidPolicyAssignmentName","message":"The policy assignment name 'Append_NSG_if_missing-4ca69cc5-3a14-4614-9d17-04e0ca2cee70' is invalid. The policy assignment name length must not exceed '24' characters."}
`

![image](https://user-images.githubusercontent.com/45152735/106885430-d9f0a180-66e2-11eb-9020-74184ea3de09.png)
![image](https://user-images.githubusercontent.com/45152735/106885394-cfcea300-66e2-11eb-8fb5-980adece43ef.png)

**Comment by ajinkya599** [comment]
@tauhid - Can you please have a look at this?
