### ISSUE TITLE
Make the Sync Logic Pipeline agnostic

### ISSUE THREAD

**Issue by NikoMix** [Azure/manage-azure-policy#47]
Currently the job is only available as Github Action. Most of the Github logic is only for debug output - as far as I've seen. It would be great if the sync logic - which is github independant - can be re-used in other Pipelines (Azure Devops, Gitlab, Jenkins, etc.) and having a Github Wrapper around that logic for this particular action.

**Comment by ajinkya599** [comment]
Hi @NikoMix, supporting this in other pipeline systems is not currently in our backlog.
So we don't plan to invest in this as of now. I would recommend copying the desired code in the action equivalent of other pipeline systems.

cc: @pulkitaggarwl, @ammohant

**Comment by NikoMix** [comment]
Would you consider a PR for this? I'd like to re-write some parts accepting interfaces, utilizing the adapter pattern with Github as initial Adapter. This would allow it to easily conribute further adaptations.

**Comment by ajinkya599** [comment]
Sure @NikoMix!
Do you want to discuss your approach here or do you want to have the discussion in the PR?

**Comment by tauhid621** [comment]
Closing this as this has been stale for some time. Please create a new issue if necessary.
