### ISSUE TITLE
Validate policies

### ISSUE THREAD

**Issue by smokedlinq** [Azure/manage-azure-policy#66]
Would be nice to be able to validate the policy files during CI/PR and not actually deploy them so there is more confidence that the changes will work during the release/cd.

**Comment by tauhid621** [comment]
@smokedlinq By validation you mean basic validations of the policy json?

**Comment by smokedlinq** [comment]
Yes something like an ARM template validation or what-if deployment.

**Comment by tauhid621** [comment]
@pulkitaggarwl Your thoughts on this?

**Comment by pulkitaggarwl** [comment]
Thanks @smokedlinq for the request. It is a valid one. 

We are adding this to our backlog. In the meanwhile would you be willing to contribute to the action for this functionality

**Comment by tauhid621** [comment]
Closing the issue as this has been idle for some time.
