### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by Meliarion** [Azure/manage-azure-policy#70]
I have a requirement to be able to deploy the same policysets/initives to multiple tenants. Is that something that this action can support or be easily modified to support?

**Comment by Meliarion** [comment]
From looking at the code, some form of paramaterisation or preprossing of the id/scope would be needed for this so it seems like something like the changes in issue #71 would be necessary as a precondition for this to work.

**Comment by tauhid621** [comment]
Closing this as this is bein tracked in #71
