### ISSUE TITLE
Sync newer policies back to the repository via PR

### ISSUE THREAD

**Issue by JustinGrote** [Azure/manage-azure-policy#74]
To align with https://github.com/azure/azops, if a policy definition/assignment is found in Azure that is newer than what is defined in the repository, then a PR should be created to merge the updated definition back to the repository to keep things in sync. Optionally allow for automerge.

**Comment by tauhid621** [comment]
This is beyond the scope of this action. The intended purpose was to have GitHub policies as the source of truth.
