### ISSUE TITLE
PolicySet and Assignment Parameters

### ISSUE THREAD

**Issue by rl-simons** [Azure/manage-azure-policy#75]
Existing action requires parameters are included within policyset.json & assign.*.json. AZ CLI & PowerShell allow parameters to be moved to a separate file to aid reusability.

Request is to:
* Replicate AZ CLI functionality of "--params" to allow creation of initiative and assignment with specific parameters.

**Comment by tauhid621** [comment]
@rl-simons Since there can be multiple parameter files we decided to keep parameters on the same json file. We were initially planning to have parameter file for each assignment but this could result in confusion so we went against this idea.

**Comment by tauhid621** [comment]
@rl-simons We will consider this again and see if we can add in our backlog.
