### ISSUE TITLE
Not exporting assignment created by my code

### ISSUE THREAD

**Issue by shashankdj** [Azure/manage-azure-policy#80]
'Allowed locations', has 4 assignment. including my assignment say 'Allowed locations Mine'.
When I use 'Export Policy Definitions' and select 'Allowed location' policy it shows all 4 assignments including mine.
Now wne I go to next step and export, after exporting it notifies, 'It exported 3 assignments'.
I verified in my GitHub also, my assignment 'Allowed locations Mine' is not exported to GitHub.

**Comment by Ganeshrockz** [comment]
@shashankdj Can you check the scopes of each of these assignments? Do they belong to the same subscription?

**Comment by shashankdj** [comment]
@Ganesh K ***@***.***>
I have 2 scenarios
1. Built in policy and existing assignment and 1 assignment created by my
code
2. Custom policy 1 assignment created by my code.

In scenario 1. It exports policy and existing assignments. But not the
assignment created by my code.
In scenario 2. It exports policy. Not an assignment.

**Comment by shashankdj** [comment]
its same subscription same scope.

**Comment by tauhid621** [comment]
Closing issue as it is stale. Do open a new one in case you are still facing this.
