### ISSUE TITLE
GitHub Actions gives deprecation warning

### ISSUE THREAD

**Issue by devenes** [Azure/manage-azure-policy#90]
The GitHub Actions workflow gives the following deprecation warning while running the action:

> Node.js 12 actions are deprecated. For more information see: github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12.

**Comment by tauhid621** [comment]
👋 The changes raised are merged in master. We'll release the changes after Holiday period in first week of January.

**Comment by devenes** [comment]
🎉 Thanks so much for your great support! Therefore, I am closing the issue as it has been merged and will be released soon.
