### ISSUE TITLE
Node.js 12 Actions Deprecated

### ISSUE THREAD

**Issue by crypticraven** [Azure/manage-azure-policy#95]
After the run completes, there's an annotation about Node.js 12 being deprecated and to use Node.js 16:

>[apply-azure-policy](https://github.com/Chester-Brown_csc/AzurePolicy/actions/runs/3840213885/jobs/6538991673)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, azure/manage-azure-policy@v0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by tauhid621** [comment]
The node version bump has been [released](https://github.com/Azure/manage-azure-policy/pull/94)
