### ISSUE TITLE
API update to support newer properties

### ISSUE THREAD

**Issue by PleaseStopAsking** [Azure/manage-azure-policy#98]
It would be nice if a new version is in the works with a new version of the api so that we could leverage newer properties of policy assignments such as `overrides`. As of now, we are unable to and the workaround is to leave them out and then manually add them afterwards. Will a lot of policies, these leads to a lot of extra work.

https://github.com/Azure/manage-azure-policy/blob/1ed950c25977c56949fee5ce2b07e6fd7aa47958/src/azure/azHttpClient.ts#L272C11-L272C21

**Comment by ryancolley** [comment]
Hi, is there any update to this issue please?
We could really do with the ability to import initiatives via newer definitions.. example:
![Screenshot 2024-03-04 at 11 38 36](https://github.com/Azure/manage-azure-policy/assets/155534086/9b439249-8c37-47de-888d-daf962d6936e)

**Comment by PleaseStopAsking** [comment]
@ryancolley its been two years since the last push to this repo. I finally gave up and moved to using the [EPAC](https://github.com/Azure/enterprise-azure-policy-as-code) module and leveraged that in my workflows with minimal work.
